name: EntrePastor
favicon: null
layout_spectrum: 0.1022
typography_spectrum: 0.63303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.05129975616000593
  lightness: 0.7234367260243744
  saturation: 0.5372034430038184
  rhythmicContrast: 0.9317486570216715
purpose: []
